export const siteConfig = {
  name: "Nirmaan Infotech",
  tagline: "Build. Grow. Go Digital.",
  description: "Nirmaan Infotech is a Pune-based technology company building high-performance websites, custom software, ERP systems, and digital solutions for businesses across Maharashtra and India.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://nirmaaninfotech.in",
  contact: {
    email: process.env.NEXT_PUBLIC_CONTACT_EMAIL || "info@nirmaaninfotech.in",
    phone: process.env.NEXT_PUBLIC_CONTACT_PHONE || "+91 8208216317",
    phoneRaw: "+918208216317",
    phoneHref: "tel:+918208216317",
    whatsapp: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || "918208216317",
    whatsappDisplay: "+91 8208216317",
    whatsappMessage: "Hello Nirmaan Infotech, I would like to discuss a website or digital project for my business.",
    whatsappUrl: "https://wa.me/918208216317?text=Hello%20Nirmaan%20Infotech%2C%20I%20would%20like%20to%20discuss%20a%20website%20or%20digital%20project%20for%20my%20business.",
    address: process.env.NEXT_PUBLIC_OFFICE_ADDRESS || "Anandnagar, Pune, Maharashtra, India",
    workingHours: "Mon - Sat: 9:00 AM - 7:00 PM IST",
  },
  social: {
    linkedin: process.env.NEXT_PUBLIC_LINKEDIN_URL || "https://linkedin.com/company/nirmaan-infotech",
    instagram: process.env.NEXT_PUBLIC_INSTAGRAM_URL || "https://instagram.com/nirmaan.infotech",
    facebook: process.env.NEXT_PUBLIC_FACEBOOK_URL || "https://facebook.com/nirmaaninfotech",
    twitter: process.env.NEXT_PUBLIC_TWITTER_URL || "https://twitter.com/nirmaaninfotech",
  },
  meta: {
    title: "Web Development Company in Pune | Nirmaan Infotech",
    description: "Nirmaan Infotech is a web development company in Pune building high-performance business websites, e-commerce stores, ERP software, and custom digital solutions for growing businesses.",
    keywords: [
      "Web Development Company Pune",
      "Website Development Company Pune",
      "Web Design Company Pune",
      "ERP Development Company Pune",
      "Custom Software Development Pune",
      "Software Development Company Pune",
      "Business Website Development Pune",
      "Digital Solutions Company Pune",
      "IT Company Pune",
      "Website Development Company Maharashtra",
      "Web Development Company India",
      "Nirmaan Infotech",
    ],
  },
};
